
;This section contains some default values to be used in source code
[DEFAULT_VALS]
NAME = 
PORT = 12001

;This section specifies maximum connections to be allowed 
[MAX_CONNECTIONS_ALLOWED]
CONNECTIONS = 100

;This section provides document root folder which is designated for holding web pages.
[DOCUMENT_ROOT]
PATH = htdocs

;This section provides directory name to be created for storing client data through POST request 
[CLIENT_DATA]
DIRECTORY = Client_Folder
POST_FILE = post_record.txt

;This section gives the file name where all client IP and cookie values are stored
[COOKIE]
FILE = all_cookies.json
