
;This section contains some default values to be used in source code
[DEFAULT_VALS]
NAME = 
PORT = 12001

;This section specifies maximum connections to be allowed 
[MAX_CONNECTIONS_ALLOWED]
CONNECTIONS = 100

;This section provides document root folder which is designated for holding web pages.
[DOCUMENT_ROOT]
PATH = htdocs
